### PR TITLE
fix: next page button UX/UI in mobile

### LINKED ISSUE #48: Next page button in agnostic table is not fully displayed in portrait mode on a mobile
Next page button in agnostic table is not fully displayed in portrait mode on a mobile

### PR DESCRIPTION
**Pull request by LiKang6688**
fixes #48

Also switching to `isModal` to check if selections are active. Needs an update to work in sense, it will be tested at the same time as this.

### CODE REVIEW

File: src/table/TableWrapper.jsx [hunk 1]
```diff
@@ -21,16 +21,28 @@ const useStyles = makeStyles({
...
     display: 'none',
   },
+  containerMobileLayout: {
+    height: 'calc(100% - 120px)',
+  },
+  paginationMobileLayout: {
+    marginTop: '-15px',
+    '& div:nth-of-type(1)': {
+      display: 'initial',
+    },
```
Comment (haxxmaxx) [inline src/table/TableWrapper.jsx:31]: What does this do?

File: src/table/TableWrapper.jsx [hunk 2]
```diff
@@ -21,16 +21,28 @@ const useStyles = makeStyles({
...
 export default function TableWrapper(props) {
   const { tableData, setPageInfo, constraints } = props;
   const { size, rows } = tableData;
+  const [tableWidth, setTableWidth] = useState();
   const [page, setPage] = useState(0);
   const [rowsPerPage, setRowsPerPage] = useState(100);
   const classes = useStyles();
   const containerMode = constraints.active ? 'containerOverflowHidden' : 'containerOverflowAuto';
   const clientMode = constraints.active && 'paginationHidden';
+  const containerLayout = tableWidth < 380 && 'containerMobileLayout';
```
Comment (haxxmaxx) [inline src/table/TableWrapper.jsx:44]: is 380 where sense-client goes into mobile mode?

File: src/table/TableWrapper.jsx [hunk 3]
```diff
@@ -49,16 +61,23 @@ export default function TableWrapper(props) {
     return null;
   }
 
+  const tableContainer = useRef();
+
+  useEffect(() => {
+    window.console.log(tableContainer.current.clientWidth, 'container');
```
Comment (haxxmaxx) [inline src/table/TableWrapper.jsx:67]: I think it's easier to pass `element` from index. It updates as soon as the size changes, so I think it would work as a dependency for useEffect

Comment (haxxmaxx) [inline src/table/TableWrapper.jsx:67]: I think it's easier to pass `element` from index. It updates as soon as the size changes, so I think it would work as a dependency for useEffect

File: src/table/TableWrapper.jsx (hunk 2 above)
Comment (LiKang6688) [reply src/table/TableWrapper.jsx:44]: it is 380px that the next page button starts to become invisible

File: src/table/TableWrapper.jsx (hunk 3 above)
Comment (LiKang6688) [reply src/table/TableWrapper.jsx:67]: good idea. I will try it.

File: src/table/TableWrapper.jsx (hunk 1 above)
Comment (LiKang6688) [reply src/table/TableWrapper.jsx:31]: it is a trick that to get the first child element of the TablePagination component that is a div.

File: src/table/TableWrapper.jsx (hunk 2 above)
Comment (haxxmaxx) [reply src/table/TableWrapper.jsx:44]: But why 380?

File: src/table/TableWrapper.jsx [hunk 4]
```diff
@@ -49,16 +61,22 @@ export default function TableWrapper(props) {
     return null;
   }
 
+  useEffect(() => {
+    const updateSize = () => setTableWidth(el.clientWidth);
+    window.addEventListener('resize', updateSize);
+    return () => window.removeEventListener('resize', updateSize);
```
Comment (haxxmaxx) [inline src/table/TableWrapper.jsx:67]: No need to add another listener since `el.clientWidth` updates on resize. So adding that the dependency array and just call `setTableWidth` should work fine

File: src/table/TableWrapper.jsx (hunk 2 above)
Comment (LiKang6688) [reply src/table/TableWrapper.jsx:44]: I just change the window size and when the window size is 380px, the next page button starts to become invisible

File: src/table/TableWrapper.jsx (hunk 4 above)
Comment (LiKang6688) [reply src/table/TableWrapper.jsx:67]: no, not really. I tried the way that you described but it does not work. I belive that the reason is that **const el = useElement();** and **render(el, {})** way to render UI.

File: src/table/TableWrapper.jsx (hunk 2 above)
Comment (haxxmaxx) [reply src/table/TableWrapper.jsx:44]: okok

Comment (haxxmaxx) [reply src/table/TableWrapper.jsx]: Changed to 400 since it gets a bit tight if you hav lik 100000 rows, the `1-100 of 100000` string becomes long
