### PR TITLE
fix: mui conflicts and overflow update

### LINKED ISSUE #37: Some styling issues in agnostic table.
Some styling issues in agnostic table.

1. Checkmark in drop down is almost overlapping the number.  
2. Arrow dropdown for selecting rows per page is too close the the line of the dropdown square
3. The height of the dropdown also does not look proportional to the content of it.

agt, drop-down
agt, drop-down2

### PR DESCRIPTION
**Pull request by haxxmaxx**
fixes #37

### CODE REVIEW

File: src/mui-setup.js [hunk 1]
```diff
@@ -1,11 +1,11 @@
 import { createGenerateClassName, createMuiTheme } from '@material-ui/core/styles';
 
-export default function muiSetup(isActive, sproutBase) {
+export default function muiSetup(sproutBase) {
   if (sproutBase.overrides) {
     /* eslint-disable no-param-reassign */
     sproutBase.overrides.MuiTableContainer.root.height = 'calc(100% - 52px)';
-    sproutBase.overrides.MuiTableContainer.root.overflow = !isActive ? 'auto' : 'hidden';
-    sproutBase.overrides.MuiPaper = { root: { height: '100%' } };
```
Comment (haxxmaxx) [inline src/mui-setup.js:8]: This was applied to the rows per page dropdown as well.

File: src/table/table.jsx [hunk 2]
```diff
@@ -9,11 +10,25 @@ import TablePagination from '@material-ui/core/TablePagination';
...
+});
+
 export default function TableWrapper(props) {
-  const { tableData, setPageInfo } = props;
+  const { tableData, setPageInfo, constraints } = props;
   const { size, columns, rows } = tableData;
   const [page, setPage] = useState(0);
   const [rowsPerPage, setRowsPerPage] = useState(100);
+  const classes = useStyles();
+  const containerMode = constraints.active ? 'containerOverflowHidden' : 'containerOverflowAuto';
```
Comment (haxxmaxx) [inline src/table/table.jsx:31]: This wasn't updating properly in. Since it changes I think it is better to keep it here. Could store it as a state, but I think it is a bit overkill

File: src/mui-setup.js (hunk 1 above)
Comment (Caele) [reply src/mui-setup.js:8]: that one drove me crazy

**Review by Caele — APPROVED** [review]
